COMMON: &common
  SECRET_KEY: 'kluabdfyabwleukfhakuwyye62498adfg'
  SECURITY_POST_LOGIN_VIEW: '/profile'
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@192.168.0.10:5432/flask_social_example_development
  ADMIN_CREDENTIALS: 'admin,password'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'

  SOCIAL_TWITTER:
    consumer_key: 'm0Cxw2cbRgkmmkP7gA'
    consumer_secret: 'ggqoWJvzOs9zujsBseblJLk2MYavrleMBNoA20u8K0M'

  SOCIAL_FACEBOOK:
    consumer_key: '310428869077361'
    consumer_secret: '1a00baeec5228865e93d4201625e8da3'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: 'a199482938d9ff482aba'
    consumer_secret: '189a51834c73b9ae638c89352049fe615995c746'
    module: 'app.github'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/