
DEVELOPMENT:
  SOCIAL_TWITTER:
    consumer_key: 'm0Cxw2cbRgkmmkP7gA'
    consumer_secret: 'ggqoWJvzOs9zujsBseblJLk2MYavrleMBNoA20u8K0M'

  SOCIAL_FACEBOOK:
    consumer_key: '310428869077361'
    consumer_secret: '1a00baeec5228865e93d4201625e8da3'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: 'a199482938d9ff482aba'
    consumer_secret: '189a51834c73b9ae638c89352049fe615995c746'
    module: 'app.github'
    request_token_params:
      scope: 'user'

PRODUCTION:
  SECRET_KEY: kluabdfyabwleukfhakuwyye62498adfg
  GOOGLE_ANALYTICS_ID: your_GA_id

  SOCIAL_TWITTER:
    consumer_key: 'm0Cxw2cbRgkmmkP7gA'
    consumer_secret: 'ggqoWJvzOs9zujsBseblJLk2MYavrleMBNoA20u8K0M'

  SOCIAL_FACEBOOK:
    consumer_key: '310428869077361'
    consumer_secret: '1a00baeec5228865e93d4201625e8da3'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: 'a199482938d9ff482aba'
    consumer_secret: '189a51834c73b9ae638c89352049fe615995c746'
    module: 'app.github'
    request_token_params:
      scope: 'user'